export enum IdentitiesList {
  PAGE_SETTING_ID_RACE = 7,
  PAGE_SETTING_ID_RUNNER = 11,
  PAGE_SETTING_ID_HORSE = 3,
}

export enum ACTIVITY_TYPE {
  READ = 1,
  CREATE = 2,
  UPDATE = 3,
  DELETE = 4,
  MERGE = 5,
}

export enum SALES_STATUS {
  READY_TO_DEPLOY = 1,
  VERIFY_REQUIRED = 2,
  PDF_REQUIRED = 3,
  IMPORT_REQUIRED = 4,
  DEPLOYED = 5,
}

export enum ORDER_STATUS {
  ORDERED = 1,
  INITIATED = 2,
  COMPLETED = 3,
  DELIVERED = 4,
  CANCELLED = 5,
  REFUNDED = 6,
}
export enum ordersStatusList {
  ORDERED = 'ORDERED', // 1
  INITIATED = 'INITIATED', // 2
  COMPLETED = 'COMPLETED', // 3
  DELIVERED = 'DELIVERED', // 4
  CANCELLED = 'CANCELLED', // 5
  REFUNDED = 'REFUNDED', // 6
}

export enum PAYMENT_STATUS {
  UNPAID = 1,
  PAID = 2,
}

export enum PRODUCT {
  SHORTLIST_STALLION_REPORT = 1,
  STALLION_MATCH_PRO_REPORT = 2,
  BROODMARE_AFFINITY_REPORT = 3,
  STALLION_MATCH_SALES_REPORT = 4,
  STALLION_AFFINITY_REPORT = 5,
  BROODMARE_SIRE_REPORT = 6,
  LOCAL_BOOST = 7,
  EXTENDED_BOOST = 8,
  PROMOTED_STALLION = 9,
  NOMINATION_ACCEPTANCE = 10,
}
