export enum productCodeList {
    REPORT_SHORTLIST_STALLION = 'REPORT_SHORTLIST_STALLION', // 1
    REPORT_STALLION_MATCH_PRO = 'REPORT_STALLION_MATCH_PRO', // 2
    REPORT_BROODMARE_AFFINITY = 'REPORT_BROODMARE_AFFINITY', // 3
    REPORT_STALLION_MATCH_SALES = 'REPORT_STALLION_MATCH_SALES', // 4
    REPORT_STALLION_AFFINITY = 'REPORT_STALLION_AFFINITY', // 5
    REPORT_BROODMARE_SIRE = 'REPORT_BROODMARE_SIRE', // 6
    BOOST_LOCAL = 'BOOST_LOCAL', // 7
    BOOST_EXTENDED = 'BOOST_EXTENDED', // 8
    PROMOTION_STALLION = 'PROMOTION_STALLION', // 9
    NOMINATION_STALLION = 'NOMINATION_STALLION', // 10
    REPORT_STALLION_BREEDING_STOCK_SALE = 'REPORT_STALLION_BREEDING_STOCK_SALE',
}
export enum PRODUCTCOVERIMAGE {
    PROMOTION_STALLION = 'StallionPageEx.png',
    REPORT_SHORTLIST_STALLION = 'SM-ShortlistReport.png',
    REPORT_STALLION_MATCH_PRO = 'SM-ProReport.png',
    REPORT_BROODMARE_AFFINITY = 'SM-BroodmareAffinity.png',
    REPORT_STALLION_MATCH_SALES = 'SM-SalesReport.png',
    REPORT_STALLION_AFFINITY = 'SM-StallionAffinity.png',
    REPORT_BROODMARE_SIRE = 'SM-BroodmareSire.png',
    BOOST_LOCAL  = 'localBoost.png',
    BOOST_EXTENDED = 'extendedBoost.png'
  
  
  }